In [1]:
import pandas as pd
import numpy as np
import urllib
import requests
import rpy2
import gc
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
loan = ["LoanStats3a","LoanStats3b","LoanStats3c","LoanStats3d",\
        "LoanStats_2016Q1","LoanStats_2016Q2","LoanStats_2016Q3",\
        "LoanStats_2016Q4","LoanStats_2017Q1","LoanStats_2017Q2"]
reject = ["RejectStatsA","RejectStatsB","RejectStatsD","RejectStats_2016Q1",\
          "RejectStats_2016Q2","RejectStats_2016Q3","RejectStats_2016Q4",\
          "RejectStats_2017Q1","RejectStats_2017Q2"]

def download(url_list):
    
    for u in url_list:
        url = ("https://resources.lendingclub.com/%s.csv.zip" % u)

        # Log and print
        operation = "Start retrieving files from " + u + "\n"
        log(operation)
        print(operation)

        # Retrieving
        filename = "/Users/CJL-RMBP/Documents/assignment3data/%s.csv.zip" % u 
        urllib.request.urlretrieve(url,filename=filename)

        # Log and print
        operation = "Done retrieving."
        log(operation)
        print(operation)
    
def log(operation):
    '''Log all the operations with a time stamp into a log file'''

    with open("log_file.txt", 'a') as f:
        data = time.ctime() + ": " + operation
        f.write(data)

download(loan)
download(reject)

In [12]:
frames = []
for u in loan:
    
    ts = pd.read_csv("~/Documents/assignment3data/%s.csv"%u,skiprows=1)
    print(ts.shape)
    frames.append(ts)
    del ts
loandata = pd.concat(frames)
gc.collect()

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(42538, 145)

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,47,123,124,125,128,129,130,133) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(188183, 145)

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,19,123,124,125,128,129,130,133) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(235631, 145)

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(421097, 145)

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(133889, 145)
(97856, 145)
(99122, 145)
(103548, 145)

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,112,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(96781, 145)

/Users/CJL-RMBP/Library/Python/3.6/lib/python/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(105453, 145)

221

In [8]:
print(loandata.shape)
loandata.head()

(1524098, 145)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,Fully Paid,n,NaN,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,1.0,NaN,NaN,3.0,0.0,13648.0,83.7%,9.0,f,0.0,0.0,5863.155187,5833.84,5000.00,863.16,0.00,0.0,0.00,Jan-2015,171.62,NaN,Oct-2017,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,Charged Off,n,NaN,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-1999,5.0,NaN,NaN,3.0,0.0,1687.0,9.4%,4.0,f,0.0,0.0,1014.530000,1014.53,456.46,435.17,0.00,122.9,1.11,Apr-2013,119.66,NaN,Oct-2016,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,Fully Paid,n,NaN,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,2.0,NaN,NaN,2.0,0.0,2956.0,98.5%,10.0,f,0.0,0.0,3005.666844,3005.67,2400.00,605.67,0.00,0.0,0.00,Jun-2014,649.91,NaN,Jun-2017,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-2011,Fully Paid,n,NaN,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-1996,1.0,35.0,NaN,10.0,0.0,5598.0,21%,37.0,f,0.0,0.0,12231.890000,12231.89,10000.00,2214.92,16.97,0.0,0.00,Jan-2015,357.48,NaN,Apr-2016,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-2011,Fully Paid,n,NaN,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-1996,0.0,38.0,NaN,15.0,0.0,27783.0,53.9%,38.0,f,0.0,0.0,4066.908161,4066.91,3000.00,1066.91,0.00,0.0,0.00,Jan-2017,67.30,NaN,Jan-2017,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
loandata.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524073e+06,1.523904e+06,1.524048e+06,1.524047e+06,767495.000000,1.524048e+06,1.524048e+06,1.524077e+06,1.524048e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.524077e+06,1.523932e+06,1524077.0,1.524048e+06,1.453801e+06,1.453801e+06,657947.000000,657948.000000,657948.000000,657948.000000,640441.000000,6.579480e+05,571467.000000,657948.000000,657948.000000,657948.000000,657909.000000,1.453801e+06,657948.000000,657947.000000,657947.000000,1.474047e+06,1.453787e+06,1.459346e+06,1.458538e+06,1.523932e+06,1.524048e+06,1.411294e+06,1.453800e+06,1.453800e+06,1.453801e+06,1.474047e+06,1.460268e+06,1.318637e+06,520064.000000,1.453801e+06,1.453801e+06,1.453801e+06,1.465487e+06,1.453801e+06,1.453801e+06,1.453801e+06,1.453800e+06,1.453801e+06,1.465487e+06,1.395094e+06,1.453801e+06,1.453801e+06,1.453801e+06,1.453648e+06,1.458920e+06,1.522712e+06,1.523972e+06,1.453801e+06,1.474047e+06,1.474047e+06,1.453801e+06
mean,1.474420e+04,1.473639e+04,1.471112e+04,4.397167e+02,7.716750e+04,1.843447e+01,3.326975e-01,6.318421e-01,33.829221,1.167851e+01,2.211964e-01,1.692056e+04,2.486790e+01,4.870090e+03,4.868319e+03,1.115009e+04,1.112543e+04,8.703965e+03,2.347409e+03,9.158100e-01,9.780279e+01,1.529190e+01,3.182313e+03,1.755787e-02,1.0,5.627776e-03,2.415158e+02,1.418924e+05,0.972714,2.837869,0.691685,1.599941,21.319895,3.572293e+04,70.322083,1.354276,2.868658,5815.737687,59.635866,3.313152e+04,0.960799,1.486263,2.125440,4.558569e+00,1.343967e+04,9.869883e+03,6.140792e+01,8.978747e-03,1.570852e+01,1.269617e+02,1.841952e+02,1.352725e+01,8.121109e+00,1.659485e+00,2.457978e+01,6.870691e+00,35.272253,5.105431e-01,3.714307e+00,5.763766e+00,4.757131e+00,8.046112e+00,8.517230e+00,8.313348e+00,1.454196e+01,5.712211e+00,1.171822e+01,8.852450e-04,3.876734e-03,9.087420e-02,2.103017e+00,9.399274e+01,4.657603e+01,1.289082e-01,5.946894e-02,1.753607e+05,5.067483e+04,2.181399e+04,4.275248e+04
std,8.735124e+03,8.731993e+03,8.737770e+03,2.572152e+02,8.603226e+04,9.811033e+00,8.995208e-01,9.402698e-01,21.893944,5.509203e+00,6.270118e-01,2.296102e+04,1.190129e+01,7.069765e+03,7.067536e+03,9.118545e+03,9.111871e+03,7.726678e+03,2.504819e+03,7.254907e+00,5.933058e+02,1.014464e+02,5.832890e+03,1.491066e-01,0.0,8.107877e-02,7.904489e+03,1.577837e+05,1.165073,3.053682,0.938173,1.611356,26.309064,4.301633e+04,23.480192,1.527753,2.624627,5550.574935,20.306186,3.655011e+04,1.482958,2.700882,2.418309,3.132985e+00,1.608401e+04,1.493859e+04,2.766084e+01,1.081367e-01,8.036299e+02,5.223266e+01,9.537061e+01,1.690343e+01,9.026861e+00,1.984723e+00,3.161756e+01,5.928648e+00,22.393584,1.332357e+00,2.277738e+00,3.348590e+00,2.966415e+00,4.761339e+00,7.359635e+00,4.571634e+00,8.066136e+00,3.260557e+00,5.512837e+00,3.140457e-02,6.601770e-02,5.110469e-01,1.808823e+00,8.915690e+00,3.591526e+01,3.755420e-01,4.272698e-01,1.781854e+05,4.834163e+04,2.159061e+04,4.373665e+04
min,5.000000e+02,5.000000e+02,0.000000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.710000e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.000000e+03,8.000000e+03,8.000000e+03,2.538100e+02,4.620000e+04,1.206000e+01,0.000000e+00,0.000000e+00,15.000000,8.000000e+00,0.000000e+00,6.273000e+03,1.600000e+01,0.000000e+00,0.000000e+00,4.312789e+03,4.291950e+03,2.873630e+03,7.436300e+02,0.000000e+00,0.000000e+00,0.000000e+00,3.019000e+02,0.000000e+00,1.0,0.000000e+00,0.000000e+00,3.004900e+04,0.000000,1.000000,0.000000,0.000000,7.000000,9.404000e+03,57.000000,0.000000,1.000000,2398.000000,46.000000,1.420000e+04,0.000000,0.000000,0.000000,2.000000e+00,3.151000e+03,1.414000e+03,4.060000e+01,0.000000e+00,0.000000e+00,1.000000e+02,1.190000e+02,4.000000e+00,3.000000e+00,0.000000e+00,6.000000e+00,2.000000e+00,16.000000,0.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,5.000000e+00,3.000000e+00,5.000000e+00,9.000000e+00,3.000000e+00,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.100000e+01,1.430000e+01,0.000000e+00,0.000000e+00,5.021500e+04,2.146900e+04,7.900000e+03,1.500000e+04
50%,1.280000e+04,1.272500e+04,1.262500e+04,3.779500e+02,6.500000e+04,1.786000e+01,0.000000e+00,0.000000e+00,30.000000,1.100000e+01,0.000000e+00,1.162200e+04,2.300000e+01,2.929600e+02,2.929600e+02,8.640820e+03,8.617270e+03,6.250000e+03,1.531400e+03,0.000000e+00,0.000000e+00,0.000000e+00,5.401000e+02,0.000000e+00,1.0,0.000000e+00,0.000000e+00,8.130700e+04,1.000000,2.000000,0.000000,1.000000,13.000000,2.369800e+04,73.000000,1.000000,2.000000,4436.000000,61.000000,2.440000e+04,0.000000,0.000000,1.000000,4.000000e+00,7.453000e+03,4.551000e+03,6.490000e+01,0.000000e+00,0.000000e+00,1.300000e+02,1.670000e+02,8.000000e+00,6.000000e+00,1.000000e+00,1.400000e+01,5.000000e+00,32.000000,0.000000e+00,3.000000e+00,5.000000e+00,4.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,1.300000e+01,5.000000e+00,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,9.760000e+01,5.000000e+01,0.000000e+00,0.000000e+00,1.135030e+05,3.803300e+04,1.530000e+04,3.212700e+04
75%,2.000000e+04,2.000000e+04,2.000000e+04,5.802100e+02,9.200000e+04,2.427000e+01,0.000000e+00,1.000000e+00,49.000000,1.400000e+01,0.000000e+00,2.054200e+04,3.200000e+01,8.033360e+03,8.029350e+03,1.543136e+04,1.539799e+04,1.200000e+04,3.007760e+03,0.000000e+00,0.000000e+00,0.000000e+00,2.857830e+03,0.000000e+00,1.0,0.000000e+00,0.000000e+00,2.113850e+05,1.000000,3.000000,1.000000,2.000000,24.000000,4.638600e+04,86.000000,2.000000,4.000000,7520.000000,74.000000,4.110000e+04,1.000000,2.000000,3.000000,6.000000e+00,1.863300e+04,1.197400e+04,8.570000e+01,0.000000e+00,0.000000e+00,1.530000e+02,2.340000e+02,1.600000e+01,1.000000e+01,3.000000e+00,2.900000e+01,1.000000e+01,51.000000,0.000000e+00,5.000000e+00,7.000000e+00,6.000000e+00,1.000000e+01,1.100000e+01,1.100000e+01,1.900000e+01,7.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.000000e+02,7.500000e+01,0.000000e+00,0.000000e+00,2.532430e+05,6.370700e+04,2.840000e+04,5.740000e+04
max,4.000000e+04,4.000000e+04,4.000000e+04,1.719830e+03,6.100000e+07,9.990000e+02,4.200000e+01,3.300000e+01,195.000000,9.700000e+01,8.600000e+01,2.904836e+06,1.760000e+02,3.982500e+04,3.970577e+04,6.155769e+04,6.151372e+04,4.000000e+04,2.681056e+04,8.759800e+02,3.944437e+04,7.002190e+03,4.214853e+04,2.000000e+01,1.0,1.400000e+01,9.152545e+06,8.524709e+06,18.000000,57.000000,25.000000,51.000000,511.000000,1.547285e+06,1000.000000,28.000000,60.000000,776843.000000,204.000000,9.999999e+06,48.000000,111.000000,49.000000,6.400000e+01,9.580840e+05,7.111400e+05,3.396000e+02,1.000000e+01,1.854080e+05,8.080000e+02,9.990000e+02,4.380000e+02,3.140000e+02,6.100000e+01,6.390000e+02,2.500000e+01,197.000000,5.100000e+01,4.700000e+01,6.300000e+01,7.100000e+01,7.900000e+01,1.590000e+02,9.100000e+01,1.280000e+02,5.900000e+01,9.700000e+01,6.000000e+00,4.000000e+00,4.200000e+01,3.200000e+01,1.000000e+02,1.000000e+02,1.200000e+01,8.500000e+01,9.999999e+06,2.921551e+06,1.105500e+06,2.101913e+06

In [16]:
loan_mv = loandata.isnull().sum(axis=0).reset_index()
loan_mv.columns = ['column_name', 'no_missing']
loan_mv['missing_ratio'] = loan_mv['no_missing'] / loandata.shape[0]
loan_mv.sort_values(by='no_missing',ascending=True, inplace=True)
loan_mv

                                    column_name  no_missing  missing_ratio
122                               hardship_flag          21       0.000014
52                             application_type          21       0.000014
20                                      purpose          21       0.000014
51                                  policy_code          21       0.000014
23                                   addr_state          21       0.000014
46                              last_pymnt_amnt          21       0.000014
44                      collection_recovery_fee          21       0.000014
137                         disbursement_method          21       0.000014
43                                   recoveries          21       0.000014
41                                total_rec_int          21       0.000014
40                              total_rec_prncp          21       0.000014
39                              total_pymnt_inv          21       0.000014
38                                  total_pymnt          21       0.000014
32                                    revol_bal          21       0.000014
37                                out_prncp_inv          21       0.000014
42                           total_rec_late_fee          21       0.000014
36                                    out_prncp          21       0.000014
17                                   pymnt_plan          21       0.000014
15                                      issue_d          21       0.000014
138                        debt_settlement_flag          21       0.000014
2                                     loan_amnt          21       0.000014
3                                   funded_amnt          21       0.000014
4                               funded_amnt_inv          21       0.000014
5                                          term          21       0.000014
6                                      int_rate          21       0.000014
7                                   installment          21       0.000014
8                                         grade          21       0.000014
9                                     sub_grade          21       0.000014
11                                   emp_length          21       0.000014
12                               home_ownership          21       0.000014
14                          verification_status          21       0.000014
16                                  loan_status          21       0.000014
35                          initial_list_status          21       0.000014
22                                     zip_code          22       0.000014
13                                   annual_inc          25       0.000016
79                                  delinq_amnt          50       0.000033
56                               acc_now_delinq          50       0.000033
31                                      pub_rec          50       0.000033
30                                     open_acc          50       0.000033
34                                    total_acc          50       0.000033
26                             earliest_cr_line          50       0.000033
25                                  delinq_2yrs          50       0.000033
27                               inq_last_6mths          51       0.000033
48                           last_credit_pull_d          87       0.000057
106                                   tax_liens         126       0.000083
78                     chargeoff_within_12_mths         166       0.000109
49                   collections_12_mths_ex_med         166       0.000109
24                                          dti         194       0.000127
33                                   revol_util         913       0.000599
105                        pub_rec_bankruptcies        1386       0.000909
45                                 last_pymnt_d        1440       0.000945
21                                        title       23345       0.015317
108                           total_bal_ex_mort       50051       0.032840
109                              total_bc_limit       50051       0.032840
74                         acc_open_past_24mths       50051       0.032840
84                                     mort_acc       50051       0.032840
98                                     num_sats       58611       0.038456
92                                  num_bc_sats       58611       0.038456
85                         mths_since_recent_bc       63830       0.041881
76                               bc_open_to_buy       64752       0.042485
104                            percent_bc_gt_75       65178       0.042765
77                                      bc_util       65560       0.043016
83                               mo_sin_rcnt_tl       70297       0.046124
70                             total_rev_hi_lim       70297       0.046124
89                        num_accts_ever_120_pd       70297       0.046124
90                               num_actv_bc_tl       70297       0.046124
91                              num_actv_rev_tl       70297       0.046124
58                                  tot_cur_bal       70297       0.046124
94                                    num_il_tl       70297       0.046124
95                                num_op_rev_tl       70297       0.046124
97                          num_rev_tl_bal_gt_0       70297       0.046124
100                                num_tl_30dpd       70297       0.046124
57                                 tot_coll_amt       70297       0.046124
101                          num_tl_90g_dpd_24m       70297       0.046124
102                          num_tl_op_past_12m       70297       0.046124
107                             tot_hi_cred_lim       70297       0.046124
110                  total_il_high_credit_limit       70297       0.046124
93                                    num_bc_tl       70297       0.046124
96                                num_rev_accts       70298       0.046124
82                        mo_sin_rcnt_rev_tl_op       70298       0.046124
81                         mo_sin_old_rev_tl_op       70298       0.046124
75                                  avg_cur_bal       70311       0.046133
103                              pct_tl_nvr_dlq       70450       0.046224
10                                    emp_title       93655       0.061449
80                           mo_sin_old_il_acct      112804       0.074014
99                             num_tl_120dpd_2m      129004       0.084643
87                        mths_since_recent_inq      205461       0.134808
47                                 next_pymnt_d      754086       0.494775
28                       mths_since_last_delinq      756603       0.496427
60                                  open_act_il      866150       0.568303
62                                  open_il_24m      866150       0.568303
64                                 total_bal_il      866150       0.568303
61                                  open_il_12m      866150       0.568303
71                                       inq_fi      866150       0.568303
67                                  open_rv_24m      866150       0.568303
68                                   max_bal_bc      866150       0.568303
66                                  open_rv_12m      866150       0.568303
73                                 inq_last_12m      866151       0.568304
59                                  open_acc_6m      866151       0.568304
72                                  total_cu_tl      866151       0.568304
69                                     all_util      866189       0.568329
63                           mths_since_rcnt_il      883657       0.579790
65                                      il_util      952631       0.625046
88               mths_since_recent_revol_delinq     1004034       0.658773
50                  mths_since_last_major_derog     1120522       0.735203
86                     mths_since_recent_bc_dlq     1156084       0.758537
29                       mths_since_last_record     1264693       0.829798
19                                         desc     1398030       0.917284
139                   debt_settlement_flag_date     1490852       0.978186
55                    verification_status_joint     1503578       0.986536
53                             annual_inc_joint     1503578       0.986536
54                                    dti_joint     1503582       0.986539
140                           settlement_status     1512865       0.992630
142                           settlement_amount     1512865       0.992630
144                             settlement_term     1512865       0.992630
143                       settlement_percentage     1512865       0.992630
141                             settlement_date     1512869       0.992632
115                            sec_app_open_acc     1516267       0.994862
117                         sec_app_open_act_il     1516267       0.994862
118                       sec_app_num_rev_accts     1516267       0.994862
119            sec_app_chargeoff_within_12_mths     1516267       0.994862
120          sec_app_collections_12_mths_ex_med     1516267       0.994862
113                      sec_app_inq_last_6mths     1516267       0.994862
111                             revol_bal_joint     1516267       0.994862
112                    sec_app_earliest_cr_line     1516267       0.994862
114                            sec_app_mort_acc     1516267       0.994862
116                          sec_app_revol_util     1516350       0.994916
136                hardship_last_payment_amount     1519246       0.996816
135              hardship_payoff_balance_amount     1519246       0.996816
133                        hardship_loan_status     1519246       0.996816
132                                hardship_dpd     1519246       0.996816
129                           hardship_end_date     1519246       0.996816
130                     payment_plan_start_date     1519246       0.996816
128                         hardship_start_date     1519246       0.996816
127                             hardship_amount     1519246       0.996816
126                               deferral_term     1519246       0.996816
125                             hardship_status     1519246       0.996816
124                             hardship_reason     1519246       0.996816
123                               hardship_type     1519246       0.996816
131                             hardship_length     1519246       0.996816
134  orig_projected_additional_accrued_interest     1519807       0.997185
121         sec_app_mths_since_last_major_derog     1521408       0.998235
0                                            id     1524077       0.999986
18                                          url     1524098       1.000000
1                                     member_id     1524098       1.000000

In [17]:
co = loan_mv[loan_mv['missing_ratio']>0.7]['column_name'].tolist()
loandata = loandata.drop(co,axis=1)

In [18]:
print(loandata.shape)
loandata.head()

(1524098, 104)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,Fully Paid,n,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,1.0,NaN,3.0,0.0,13648.0,83.7%,9.0,f,0.0,0.0,5863.155187,5833.84,5000.00,863.16,0.00,0.0,0.00,Jan-2015,171.62,NaN,Oct-2017,0.0,1.0,Individual,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,N,Cash,N
1,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,Charged Off,n,car,bike,309xx,GA,1.00,0.0,Apr-1999,5.0,NaN,3.0,0.0,1687.0,9.4%,4.0,f,0.0,0.0,1014.530000,1014.53,456.46,435.17,0.00,122.9,1.11,Apr-2013,119.66,NaN,Oct-2016,0.0,1.0,Individual,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,N,Cash,N
2,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,Fully Paid,n,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,2.0,NaN,2.0,0.0,2956.0,98.5%,10.0,f,0.0,0.0,3005.666844,3005.67,2400.00,605.67,0.00,0.0,0.00,Jun-2014,649.91,NaN,Jun-2017,0.0,1.0,Individual,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,N,Cash,N
3,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-2011,Fully Paid,n,other,personel,917xx,CA,20.00,0.0,Feb-1996,1.0,35.0,10.0,0.0,5598.0,21%,37.0,f,0.0,0.0,12231.890000,12231.89,10000.00,2214.92,16.97,0.0,0.00,Jan-2015,357.48,NaN,Apr-2016,0.0,1.0,Individual,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,N,Cash,N
4,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-2011,Fully Paid,n,other,Personal,972xx,OR,17.94,0.0,Jan-1996,0.0,38.0,15.0,0.0,27783.0,53.9%,38.0,f,0.0,0.0,4066.908161,4066.91,3000.00,1066.91,0.00,0.0,0.00,Jan-2017,67.30,NaN,Jan-2017,0.0,1.0,Individual,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,N,Cash,N

In [20]:
loandata.to_csv("./loandata.csv",index=None)

In [21]:
del loandata
gc.collect()

714

In [8]:
reject = ["RejectStatsA","RejectStatsB","RejectStatsD","RejectStats_2016Q1",\
          "RejectStats_2016Q2","RejectStats_2016Q3","RejectStats_2016Q4",\
          "RejectStats_2017Q1","RejectStats_2017Q2"]
frames_2 = []
for u in reject:
    
    ts = pd.read_csv("~/Documents/assignment3data/%s.csv"%u,skiprows=1)
    print(ts.shape)
    frames_2.append(ts)
    del ts
rejdata = pd.concat(frames_2)
gc.collect()

(755491, 9)
(2694642, 9)
(2859379, 9)
(1096204, 9)
(996561, 9)
(1272619, 9)
(1404490, 9)
(1379756, 9)
(1665309, 9)

56

In [9]:
print(rejdata.shape)
rejdata.head()

(14124451, 9)

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,693.0,10%,481xx,NM,4 years,0.0
1,1000.0,2007-05-26,Consolidating Debt,703.0,10%,010xx,MA,< 1 year,0.0
2,11000.0,2007-05-27,Want to consolidate my debt,715.0,10%,212xx,MD,1 year,0.0
3,6000.0,2007-05-27,waksman,698.0,38.64%,017xx,MA,< 1 year,0.0
4,1500.0,2007-05-27,mdrigo,509.0,9.43%,209xx,MD,< 1 year,0.0

In [10]:
rejdata.to_csv("./rejdata.csv",index=None)

In [11]:
del rejdata
gc.collect()

222